name: ITO CI

on:
  # We want to trigger the build & test pipelines in every branch.
  push:
    # But do no run the pipeline when only `md` files are modified.
    paths-ignore:
      - '**.md'

  # We want to trigger the build & test pipelines in every pull request.
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Enables color display for `cargo`
  CARGO_TERM_COLOR: always

  # Enables color display for js cli app (based on `chalk`)
  # FORCE_COLOR: 1

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry/cache
          ~/.cargo/registry/index
          target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('Cargo.lock') }}
    - run: rustup target add wasm32-unknown-unknown
    - run: cargo build --target wasm32-unknown-unknown --release
