name: rust / test

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        node-version: [15.x]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          default: true
          override: true

      - name: Use Cache
        uses: Swatinem/rust-cache@v1

      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --color always --target ${{ matrix.target }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: chmod +x ./build.sh && ./build.sh
      - run: npm install -g jest
      - run: cd src/sandbox && npm install & cd ../../
      - run: cd src/sandbox/nearcore && make sandbox & cd ../../
      - run: cd src/sandbox && jest

